### ISSUE TITLE
Marriott Marquis on Logistics Page

### ISSUE THREAD

**Issue by mconlon17** [vivoconference/vivo2017#14]
The image "Getting Around New York" has Marriott Marquis in it several times and prominently.  Might be better to have a different image tio avoid confusion.  Nothing about the conference involves the Marriott Marquis.

**Comment by grahamtriggs** [comment]
Changed to Radio City (I don't have many good night photos)

**Comment by mconlon17** [comment]
Very nice.  Closing issue.
