### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by vioil** [vivoconference/vivo2017#2]
Please add the CoC under the Home tab. Text:

VIVO Code of Conduct

VIVO organizes an annual conference for the benefit of its supporters and for the advancement of research and scholarship in the variety of disciplines and professions they represent. VIVO works actively toward the creation of a more diverse, welcoming, and inclusive global community of scholars and practitioners, and is therefore dedicated to the creation of a safe, respectful, and collegial conference experience for all attendees.

Open, critically engaged, and often challenging discourse is expected to flourish at VIVO conferences. VIVO participants come from all over the world and bring with them a wide variety of professional, personal, and social backgrounds. Participants are encouraged to respect and celebrate cultural and linguistic differences, and to be mindful of the international nature of our community in preparing presentations and engaging in conversation. There is no place at VIVO meetings for harassment or intimidation based on race, religion, ethnicity, language, gender identity or expression, sexual orientation, physical or cognitive ability, age, appearance, or other group status. Unsolicited physical contact, unwelcome sexual attention, and bullying behavior are likewise unacceptable. Constitutionally protected expression cannot be considered harassment under this code.

Conference organizers are listed in the program and can be identified by their name badges. In the event a participant has been made to feel unsafe or unwelcome at a VIVO event, they are always available to assist.

**Comment by grahamtriggs** [comment]
https://vivoconference.github.io/cod/

linked from footer
