### ISSUE TITLE
GDG DevFest logo - please remove

### ISSUE THREAD

**Issue by vioil** [vivoconference/vivo2017#28]
<img width="452" alt="vivopage" src="https://cloud.githubusercontent.com/assets/3239996/25057766/4f6f83d0-2138-11e7-9164-e2f04bcd7ca7.png">

<img width="259" alt="vivopagegdg" src="https://cloud.githubusercontent.com/assets/3239996/25057788/8753c590-2138-11e7-8e0d-11e7da8d79f5.png">

It's on top left and bottom right side of the page. Please remove them.

**Comment by aviggio** [comment]
Hi @vioil -- I'm not seeing that GDG logo displayed on the live VIVO conf site, but maybe it is only on specific page(s)? Can you include a URL? 

I've checked http://vivoconference.org/ in Chrome, Safari and Firefox on my Mac, but maybe my browsers have all cached the VIVO logo and there is indeed an issue. I will say that the VIVO site renders differently when I run my local development clone ('jekyll serve -w'). That local copy does display the GDG logo.

@grahamtriggs any ideas here? I don't have much experience with Jekyll, but will bet this is a known issue and easy fix.

- Alex

**Comment by aviggio** [comment]
The file **vivoconference.github.io/css/main.css** does seem to correctly reference the VIVO logo. Maybe your browser has cached the default GDG main.css somehow?

```
.logo {
    background-image: url("../img/sprites/vivo.png");
    background-repeat: no-repeat
}
```

The original GDG logos are found under ./img/sprites and ./img/partners, so I'll do some investigation later as might be best to remove these files to avoid caching issues?

https://github.com/vivoconference/vivoconference.github.io/blob/master/img/sprites/logos.png

**Comment by vioil** [comment]
That's interesting since this is on my new computer. I'm still seeing it.

**Comment by grahamtriggs** [comment]
Alex commited a new main.css. I rolled it back.

Violeta, do a forced refresh.

**Comment by aviggio** [comment]
Thanks @grahamtriggs -- I hadn't edited main.css to my knowledge since cloning your original conf repo, so any ideas why my local copy changed? Looking at the diff on my commit, it looks like my main.css was an "optimized" version of some sort. Maybe something wrong I'm doing with Jekyll?

I clearly wasn't paying enough attention with my commit so apologies for that mistake, and I'll be careful in case a modified main.css tries to sneak back in.
