### ISSUE TITLE
Add Katie and Ying's invited speaker info

### ISSUE THREAD

**Issue by aviggio** [vivoconference/vivo2017#39]
Copy to use:

> Katie Frey is the Assistant Head and Digital Technologies Development Librarian at the Harvard-Smithsonian Center for Astrophysics, where she has worked since 2012.   One of her primary projects has been leading the development of the Unified Astronomy Thesaurus, a community supported linked data vocabulary for sorting, filtering, and exploring astronomical literature, data sets, images, etc.  She also leads initiatives such as the digitization of logbooks written by women computers who worked at the Harvard College Observatory in the mid to late 1800s and the development of a tools, devices, and maker collection for exploration and prototyping.  Katie holds a Master's in Library and Information Science from the University of Pittsburgh and a BS in Astronomy from San Diego State University.

Headshot image here:

https://drive.google.com/file/d/0BxuFJij56yMQdU5TelhrNnJRZnFMZ1FmMHlBQjRxZzhHMjZN/view?usp=sharing

**Comment by vioil** [comment]
Alex, we have another invited speaker that Terrie got so let's wait for her info so we can post them together. Sounds good?

**Comment by aviggio** [comment]
Will do! I'm traveling today, but should have time tonight or tomorrow morning.

**Comment by aviggio** [comment]
@vioil -- I think there's a typo in Katie's bio so I attempted to fix in place -- reads above "...by women computers who worked..." changed to "women computer programmers", but might have guessed wrong.

**Comment by vioil** [comment]
That's the text i got from her. Please change it to the one "women computer programmers" you suggest. Sorry I didn't catch that.
