### ISSUE TITLE
optimize home page for mobile

### ISSUE THREAD

**Issue by vioil** [vivoconference/vivo2017#60]
Does the home page looks like this for you @grahamtriggs @aviggio 
![20170521_162416](https://cloud.githubusercontent.com/assets/3239996/26287512/c6b8eb62-3e42-11e7-8da4-4d7b6cd88f93.png)

**Comment by grahamtriggs** [comment]
OK, try it now

**Comment by vioil** [comment]
now looks good, but the text about registration and workshops is gone, or I just don't see it?

**Comment by vioil** [comment]
let me add the screenshot here

![20170526_143432](https://cloud.githubusercontent.com/assets/3239996/26509931/973b878c-4220-11e7-8e0a-46826a6e77f5.png)
