### ISSUE TITLE
Add OpenVIVO flyer to the website so we can link to it in announcements 

### ISSUE THREAD

**Issue by vioil** [vivoconference/vivo2017#62]
here is the pdf

[VIVO17 OpenVIVO Flyer.pdf](https://github.com/vivoconference/vivoconference.github.io/files/1023573/VIVO17.OpenVIVO.Flyer.pdf)

**Comment by aviggio** [comment]
Hi @vioil  -- does it make sense to add a News item about OpenVIVO borrowing text from your planned email?

**Comment by vioil** [comment]
I think Julia and Carol have this on the agenda in June so we should post it then.

**Comment by aviggio** [comment]
Sounds good. What do you think of the News item idea?

**Comment by vioil** [comment]
Sorry if I wasn't clear, but yes we should post a news item in June so Julia and Carol can link to it in their announcement. I am saying the news item we write needs to go out in June so we are coordinated with marketing.

**Comment by vioil** [comment]
@aviggio since June news item didn’t happened around openvivo please add the PDF from above asap. I need to send instructions to all presenters later today or tomorrow morning. Please ping me when you are done so I can go ahead and send the email. Thank you!
