### ISSUE TITLE
add program reviewers to the website

### ISSUE THREAD

**Issue by vioil** [vivoconference/vivo2017#64]
Add the page under the Program tab please:

The Program Chair, Violeta Ilik, and the Vice-Chair, Eric Meeks, would like to thank the distinguished group of experts for helping us build a strong program for the VIVO17 Conference. 
The reviewers are listed in alphabetical order:

Paul Albert - Weill Cornell Medicine	 
Lauren Gala - University of Pennsylvania	 
Kristi Holmes - Northwestern University Feinberg School of Medicine
Violeta Ilik - Northwestern University Feinberg School of Medicine	 
Huda Kahn - Cornell University
Dean Krafft - Cornell University
Ted Lawless - Brown University
Brian Lowe - Ontocale SRL
Steven McCauley -  Brown University
Eric Meeks - University of California San Francisco 
Mark Newton - Columbia University
Andi Ogier - Virginia Tech
Simon Porter - Digital Science
Barlett Ragon - University of Viriginia
Jean Rainwater - Brown University
Hannah Sommers - George Washington University
Julie Speer - Virginia Tech
Graham Triggs - DuraSpace
Julia Trimmer - Duke University
Alex Viggio - University of Colorado Boulder 
Terrie Rose Wheeler - Weill Cornell Medicine

**Comment by aviggio** [comment]
Hi @vioil -- just seeing this. Not sure best way to add to the current Program page (/schedule) which is auto-generated from other data files. Could we add a news item page about this instead, or maybe @grahamtriggs has another suggestion based on his experiments/tweaks of the Jekyll templates?

**Comment by vioil** [comment]
@aviggio @grahamtriggs  please add it somewhere prominent since we need to acknowledge the help. If it can be somehow collocated with the program tab, adding a dropdown menu that would be great.

**Comment by grahamtriggs** [comment]
The program page should be left to displaying the program. We have a "team" page, which is where we should acknowledge people involved in putting on the conference - including reviewers. Just like there would be one page with all this information in a printed program.

**Comment by vioil** [comment]
ok, that's good - let's do that then. thanks!

**Comment by vioil** [comment]
@grahamtriggs please do this asap. Thank you in advance!
