### ISSUE TITLE
add people to Don's workshop

### ISSUE THREAD

**Issue by vioil** [vivoconference/vivo2017#67]
since i cannot assign tickets to anyone on this repo I will tag you both @grahamtriggs @aviggio 

Please list the following people [note that Don and Simon are already listed]:

Don Elsborg – University of Colorado Boulder
Benjamin Gross - UNAVCO
Simon Porter – Digital Science
Violeta Ilik – Northwestern University Feinberg School of Medicine
Paul Frank – Library of Congress
Muhammad Javed – Cornell University
John Fereira – Cornell University

**Comment by grahamtriggs** [comment]
done

**Comment by vioil** [comment]
Please add John A. Fereira and delete the duplicate entry for Javed. thanks!
