### ISSUE TITLE
Switch talks

### ISSUE THREAD

**Issue by vioil** [vivoconference/vivo2017#75]
@aviggio please switch Simon Porter's talk with Paul and Michael's Thursday talk at 11:00 titled: Using Field-Normalized Citation Impact to Predict Future Academic Success - Simon Porter needs to switch his Friday talk to Thursday.

**Comment by vioil** [comment]
@aviggio note the new change bellow:

Thursday at 4:00: Simon and John, “Using Field-Normalized Citation Impact to Predict Future Academic Success.”

Friday at 10:30: Paul and Michael, “Dynamically generating T32 training documents using structured data”

Friday at 11:00: Lamont and Julia, “Engaging Faculty and Scholars User Community using Diverse Outreach Methods and Analytics”

**Comment by aviggio** [comment]
hi @vioil -- I think you meant Simon and John's talk on "Gaining strategic insight..." (id: 120) should move to Thursday at 4:00, in place of Julia and Lamont's session (id: 115), which moves into Paul and Ayesha's (id: 123) Friday time slot and bumps them into Simon's emptied slot?
